# Menus
menu:
  主页: .
  目录: archives
  旧站: http://blog.csdn.net/xeseo
  关于我: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: edisonxu@outlook.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Edison Xu
        author_title: 懂得前端和移动，设计过架构，做过管理，也搞过自动化和运维，明白各种测试，知晓处理大数据。保持危机感和谦逊，方能更进一步
        location: 中国 - 上海
        follow: http://edisonxu.org/about
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: https://github.com/EdisonXu
        envelope: mailto:edisonxu@outlook.com
        weixin: css/images/myweixin.jpg
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - board
    #- recent_posts
    - category
    - hot_articles
    - recent_comments
    - archive
    # - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan:  # 2128296 # enter youyan uid here
    yungentie: 5b17b705ee04468c8699e7e4e10d97d6

# Share
share:  bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justified-gallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        SpringCloud中文社区: http://bbs.springcloud.cn
        周立|Spring Cloud: http://itmuch.com
        程序猿DD: http://blog.didispace.com
        许进|沉思录: http://blog.xujin.org
        EdisonXu: http://edisonxu.org
